default_context:
    author_name: "Grant Nestor"
    author_email: "grantnestor@gmail.com"
    mime_type: "application/vnd.dataresource+json"
    file_extension: "table.json"
    mime_short_name: "JSONTable"
    extension_name: "jupyterlab_table"
